# Generated by Django 3.1.3 on 2024-05-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20240518_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Technology', 'Technology'), ('Lifestyle', 'Lifestyle'), ('Education', 'Education'), ('Travel', 'Travel'), ('Food', 'Food'), ('Sports', 'Sports'), ('Finance', 'Finance'), ('Entertainment', 'Entertainment'), ('News', 'News')], max_length=50),
        ),
    ]
