# Generated by Django 3.1.3 on 2024-03-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_auto_20210821_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='appointment_slot',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
