# Generated by Django 3.1.3 on 2024-03-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_auto_20240324_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
    ]
