# Generated by Django 3.1.3 on 2024-03-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_auto_20240324_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('hospital_address', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='doctor_pics/')),
                ('speciality', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('experience', models.IntegerField()),
                ('availability_days', models.CharField(max_length=100)),
                ('free_slots', models.CharField(max_length=200)),
            ],
        ),
    ]
