# Generated by Django 3.1.3 on 2024-04-11 05:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_doctoravailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='availability_days',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='description',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='free_slots',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='hospital_address',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='name',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='speciality',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.doctor'),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='end_time',
            field=models.TimeField(default='17:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='start_time',
            field=models.TimeField(default='17:00'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.patient')),
            ],
        ),
    ]
