# Generated by Django 3.1.3 on 2024-04-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0020_auto_20240413_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('awaiting_confirmation', 'Awaiting Confirmation')], default='pending', max_length=100),
        ),
    ]
