# Generated by Django 3.1.3 on 2024-04-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0021_auto_20240423_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
