# Generated by Django 3.1.3 on 2024-04-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0023_auto_20240424_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.FileField(upload_to='receipts/'),
        ),
    ]
